"""initial schema

Revision ID: 070560627f5f
Revises: 
Create Date: 2026-09-07 12:13:02.591503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '070560627f5f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.String(length=60), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('device_id', sa.String(length=60), nullable=True),
    sa.Column('device_ip', sa.String(length=45), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_action_device', 'audit_logs', ['action', 'device_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_ts', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_user', 'audit_logs', ['username'], unique=False)
    op.create_table('device_networks',
    sa.Column('cidr', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_single_ip', sa.Boolean(), nullable=False),
    sa.Column('exclude_ips', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_networks')),
    sa.UniqueConstraint('cidr', name=op.f('uq_device_networks_cidr'))
    )
    op.create_table('devices',
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('network_cidr', sa.String(length=64), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('mac_address', sa.String(length=32), nullable=True),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('serial_number', sa.String(length=200), nullable=True),
    sa.Column('firmware_version', sa.String(length=120), nullable=True),
    sa.Column('platform', sa.String(length=120), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('vendor', sa.String(length=120), nullable=True),
    sa.Column('device_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detection_state', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detection_evidence', sa.JSON(), nullable=False),
    sa.Column('protocol_name', sa.String(length=60), nullable=True),
    sa.Column('adapter_name', sa.String(length=120), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_attendance_candidate', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_online_at', sa.DateTime(), nullable=True),
    sa.Column('last_offline_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(length=30), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('connect_timeout_s', sa.Float(), nullable=False),
    sa.Column('read_timeout_s', sa.Float(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('backoff_base_s', sa.Float(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('sync_interval_min', sa.Integer(), nullable=True),
    sa.Column('auto_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('extra_config', sa.JSON(), nullable=False),
    sa.Column('raw_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    op.create_index(op.f('ix_devices_ip_address'), 'devices', ['ip_address'], unique=False)
    op.create_index(op.f('ix_devices_status'), 'devices', ['status'], unique=False)
    op.create_table('discovery_jobs',
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('target', sa.String(length=80), nullable=False),
    sa.Column('requested_by', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('total_hosts', sa.Integer(), nullable=False),
    sa.Column('scanned_hosts', sa.Integer(), nullable=False),
    sa.Column('found_hosts', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovery_jobs'))
    )
    op.create_index('ix_discjob_ts', 'discovery_jobs', ['started_at'], unique=False)
    op.create_index(op.f('ix_discovery_jobs_status'), 'discovery_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_discovery_jobs_target'), 'discovery_jobs', ['target'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('system_users',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_users'))
    )
    op.create_index(op.f('ix_system_users_role'), 'system_users', ['role'], unique=False)
    op.create_index(op.f('ix_system_users_username'), 'system_users', ['username'], unique=True)
    op.create_table('device_capabilities',
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('capability', sa.String(length=80), nullable=False),
    sa.Column('supported', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_capabilities_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_capabilities')),
    sa.UniqueConstraint('device_id', 'capability', name='uq_device_cap')
    )
    op.create_index(op.f('ix_device_capabilities_device_id'), 'device_capabilities', ['device_id'], unique=False)
    op.create_table('device_credentials',
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('secret_ciphertext', sa.Text(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_credentials_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_credentials'))
    )
    op.create_index(op.f('ix_device_credentials_device_id'), 'device_credentials', ['device_id'], unique=False)
    op.create_table('device_protocols',
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('transport', sa.String(length=8), nullable=False),
    sa.Column('service', sa.String(length=60), nullable=True),
    sa.Column('protocol_guess', sa.String(length=80), nullable=True),
    sa.Column('protocol_state', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('banner', sa.Text(), nullable=True),
    sa.Column('http_headers', sa.JSON(), nullable=False),
    sa.Column('html_title', sa.String(length=500), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_protocols_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_protocols')),
    sa.UniqueConstraint('device_id', 'port', 'transport', name='uq_device_proto')
    )
    op.create_index(op.f('ix_device_protocols_device_id'), 'device_protocols', ['device_id'], unique=False)
    op.create_table('device_raw_data',
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('content_type', sa.String(length=80), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('payload_b64', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_raw_data_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_raw_data'))
    )
    op.create_index(op.f('ix_device_raw_data_device_id'), 'device_raw_data', ['device_id'], unique=False)
    op.create_index('ix_raw_device_ts', 'device_raw_data', ['device_id', 'captured_at'], unique=False)
    op.create_table('device_users',
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('user_id_on_device', sa.String(length=64), nullable=False),
    sa.Column('device_user_sn', sa.Integer(), nullable=True),
    sa.Column('employee_code', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('card_number', sa.String(length=64), nullable=True),
    sa.Column('password_status', sa.String(length=40), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('privilege_level', sa.Integer(), nullable=True),
    sa.Column('group_number', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('fingerprint_count', sa.Integer(), nullable=True),
    sa.Column('face_enabled', sa.Boolean(), nullable=False),
    sa.Column('card_enabled', sa.Boolean(), nullable=False),
    sa.Column('password_enabled', sa.Boolean(), nullable=False),
    sa.Column('verification_mode', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('device_user_raw_data', sa.JSON(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_users_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_users')),
    sa.UniqueConstraint('device_id', 'user_id_on_device', name='uq_device_user_uid')
    )
    op.create_index('ix_device_user_employee', 'device_users', ['device_id', 'employee_code'], unique=False)
    op.create_index(op.f('ix_device_users_device_id'), 'device_users', ['device_id'], unique=False)
    op.create_table('discovery_results',
    sa.Column('discovery_job_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=60), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('reachable', sa.Boolean(), nullable=False),
    sa.Column('open_ports', sa.JSON(), nullable=False),
    sa.Column('icmp_reachable', sa.Boolean(), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('mac_address', sa.String(length=32), nullable=True),
    sa.Column('http_headers', sa.JSON(), nullable=False),
    sa.Column('html_title', sa.String(length=500), nullable=True),
    sa.Column('banners', sa.JSON(), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('detection_state', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('probed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['discovery_job_id'], ['discovery_jobs.id'], name=op.f('fk_discovery_results_discovery_job_id_discovery_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovery_results'))
    )
    op.create_index(op.f('ix_discovery_results_discovery_job_id'), 'discovery_results', ['discovery_job_id'], unique=False)
    op.create_index('ix_discres_job_host', 'discovery_results', ['discovery_job_id', 'ip_address'], unique=False)
    op.create_index('ix_discres_ts', 'discovery_results', ['probed_at'], unique=False)
    op.create_table('sync_jobs',
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('requested_by', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_sync_jobs_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_jobs'))
    )
    op.create_index(op.f('ix_sync_jobs_device_id'), 'sync_jobs', ['device_id'], unique=False)
    op.create_index(op.f('ix_sync_jobs_status'), 'sync_jobs', ['status'], unique=False)
    op.create_index('ix_syncjob_ts', 'sync_jobs', ['started_at'], unique=False)
    op.create_table('attendance_logs',
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('fingerprint', sa.String(length=200), nullable=False),
    sa.Column('device_event_id', sa.String(length=100), nullable=True),
    sa.Column('user_id_on_device', sa.String(length=64), nullable=True),
    sa.Column('user_sn', sa.Integer(), nullable=True),
    sa.Column('employee_code', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('verification_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('work_code', sa.Integer(), nullable=True),
    sa.Column('door_id', sa.String(length=40), nullable=True),
    sa.Column('raw_event', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_attendance_logs_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['device_users.id'], name=op.f('fk_attendance_logs_user_id_device_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_logs')),
    sa.UniqueConstraint('device_id', 'fingerprint', name='uq_attlog_fingerprint')
    )
    op.create_index(op.f('ix_attendance_logs_device_id'), 'attendance_logs', ['device_id'], unique=False)
    op.create_index(op.f('ix_attendance_logs_event_time'), 'attendance_logs', ['event_time'], unique=False)
    op.create_index(op.f('ix_attendance_logs_event_type'), 'attendance_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_attendance_logs_fingerprint'), 'attendance_logs', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_attendance_logs_user_id'), 'attendance_logs', ['user_id'], unique=False)
    op.create_index('ix_attlog_device_time', 'attendance_logs', ['device_id', 'event_time'], unique=False)
    op.create_index('ix_attlog_employee', 'attendance_logs', ['employee_code'], unique=False)
    op.create_index('ix_attlog_event_time', 'attendance_logs', ['event_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attlog_event_time', table_name='attendance_logs')
    op.drop_index('ix_attlog_employee', table_name='attendance_logs')
    op.drop_index('ix_attlog_device_time', table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_user_id'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_fingerprint'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_event_type'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_event_time'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_device_id'), table_name='attendance_logs')
    op.drop_table('attendance_logs')
    op.drop_index('ix_syncjob_ts', table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_status'), table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_device_id'), table_name='sync_jobs')
    op.drop_table('sync_jobs')
    op.drop_index('ix_discres_ts', table_name='discovery_results')
    op.drop_index('ix_discres_job_host', table_name='discovery_results')
    op.drop_index(op.f('ix_discovery_results_discovery_job_id'), table_name='discovery_results')
    op.drop_table('discovery_results')
    op.drop_index(op.f('ix_device_users_device_id'), table_name='device_users')
    op.drop_index('ix_device_user_employee', table_name='device_users')
    op.drop_table('device_users')
    op.drop_index('ix_raw_device_ts', table_name='device_raw_data')
    op.drop_index(op.f('ix_device_raw_data_device_id'), table_name='device_raw_data')
    op.drop_table('device_raw_data')
    op.drop_index(op.f('ix_device_protocols_device_id'), table_name='device_protocols')
    op.drop_table('device_protocols')
    op.drop_index(op.f('ix_device_credentials_device_id'), table_name='device_credentials')
    op.drop_table('device_credentials')
    op.drop_index(op.f('ix_device_capabilities_device_id'), table_name='device_capabilities')
    op.drop_table('device_capabilities')
    op.drop_index(op.f('ix_system_users_username'), table_name='system_users')
    op.drop_index(op.f('ix_system_users_role'), table_name='system_users')
    op.drop_table('system_users')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_discovery_jobs_target'), table_name='discovery_jobs')
    op.drop_index(op.f('ix_discovery_jobs_status'), table_name='discovery_jobs')
    op.drop_index('ix_discjob_ts', table_name='discovery_jobs')
    op.drop_table('discovery_jobs')
    op.drop_index(op.f('ix_devices_status'), table_name='devices')
    op.drop_index(op.f('ix_devices_ip_address'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('device_networks')
    op.drop_index('ix_audit_user', table_name='audit_logs')
    op.drop_index('ix_audit_ts', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_action_device', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
